name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.55.2/golangci-lint-1.55.2-linux-amd64.tar.gz | tar -xz -C /tmp
        sudo mv /tmp/golangci-lint-*/golangci-lint /usr/local/bin/

    - name: Format Go code (go fmt)
      run: go fmt ./...

    - name: Lint Go code
      run: golangci-lint run --timeout 5m

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
